#cloud-config

package_update: true
package_upgrade: true
preserve_hostname: false
manage_etc_hosts: false

packages:
  - jq
  - curl

users:
  - name: jay
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ssh_public_key}

runcmd:
  - systemctl start ssh
  - hostnamectl set-hostname ${node}.example.com