---
- hosts: masters,workers
  remote_user: jay
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  tasks:
    - name: update hosts files in each node, need a better way of doing this
      shell: |
        echo "192.168.193.20  master.example.com  master" >> /etc/hosts
        echo "192.168.193.30  worker0.example.com  worker-0" >> /etc/hosts
        echo "192.168.193.31  worker1.example.com  worker-1" >> /etc/hosts

    - name: disable firewall to make it easy for now
      shell: sudo ufw disable

    - name: disable swap
      shell: |
        sudo swapoff -a
        sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: allow iptables see bridge traffic
      copy:
        dest: "/etc/modules-load.d/k8s.conf"
        content: |
          overlay
          br_netfilter

    - name: modprobe
      shell: |
        sudo modprobe overlay
        sudo modprobe br_netfilter

    - name: more bridge traffic stuff
      copy:
        dest: "/etc/sysctl.d/k8s.conf"
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1

    - name: apply new settings without reboot
      shell: sudo sysctl --system

    - name: install cri-o
      shell: |
        export OS=xUbuntu_22.04
        export CRIO_VERSION=1.26

        echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /"|sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$CRIO_VERSION/$OS/ /"|sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$CRIO_VERSION.list

        curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$CRIO_VERSION/$OS/Release.key | sudo apt-key --keyring /etc/apt/trusted.gpg.d/libcontainers.gpg add -
        curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | sudo apt-key --keyring /etc/apt/trusted.gpg.d/libcontainers.gpg add -

        sudo apt-get update
        sudo apt-get install cri-o cri-o-runc cri-tools -y

    - name: start cri-o
      shell: |
        sudo systemctl daemon-reload
        sudo systemctl enable crio --now

    - name: sysctl params setup
      copy:
        dest: "/etc/sysctl.d/99-kubernetes-cri.conf"
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: apply new settings, again
      shell: sudo sysctl --system

    - name: configure dependencies and add k8 repos
      shell: |
        sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update

    - name: install kubelet, kubeadm and kubectl only when the apt process isn't locked
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

    - name: pin kubelet, kubeadm and kubectl versions
      shell: sudo apt-mark hold kubelet kubeadm kubectl

- hosts: masters
  become: yes

  tasks:
    - name: initialise cluster with kubeadm in master node
      shell: sudo kubeadm init

    - name: setup kubectl access as normal user
      become: yes
      become_user: jay
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: setup CNI, giving Weave Net a go
      become: yes
      become_user: jay
      shell: |
        kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

    - name: generate the token for joining the worker nodes
      become: yes
      become_user: jay
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: write join command to a file
      become: yes
      copy:
        dest: "/tmp/kubernetes_join_command.sh"
        content: "{{ kubernetes_join_command.stdout_lines[0] }}"

    - name: fetch join command file to the deploying machine
      become: yes
      ansible.builtin.fetch:
        src: "/tmp/kubernetes_join_command.sh"
        dest: "/tmp/kubernetes_join_command.sh"
        flat: yes

- hosts: workers
  become: yes

  tasks:
    - name: copy k8 cluster join code into worker nodes
      become: yes
      copy:
        src: /tmp/kubernetes_join_command.sh
        dest: /tmp/kubernetes_join_command.sh
        owner: root
        mode: 0777

    - name: join the Worker nodes to the cluster.
      become: yes
      become_user: jay
      shell: sudo sh /tmp/kubernetes_join_command.sh
      register: joined_or_not