---
- hosts: masters,workers
  remote_user: jay
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes

  tasks:
    - name: update hosts files in each node, need a better way of doing this
      ansible.builtin.shell: |
        echo "192.168.193.20  master.example.com  master" >> /etc/hosts
        echo "192.168.193.30  worker0.example.com  worker-0" >> /etc/hosts
        echo "192.168.193.31  worker1.example.com  worker-1" >> /etc/hosts

    - name: disable firewall to make it easy for now
      ansible.builtin.shell: |
        sudo ufw disable

    - name: disable swap
      ansible.builtin.shell: |
        sudo swapoff -a
        sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: allow iptables see bridge traffic
      copy:
        dest: "/etc/modules-load.d/k8s.conf"
        content: |
          overlay
          br_netfilter

    - name: modprobe
      ansible.builtin.shell: |
        sudo modprobe overlay
        sudo modprobe br_netfilter

    - name: more bridge traffic stuff
      copy:
        dest: "/etc/sysctl.d/k8s.conf"
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1

    - name: apply new settings without reboot
      ansible.builtin.shell: |
        sudo sysctl --system

    - name: setup cri-o
      ansible.builtin.shell: |
        sudo echo "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        sudo echo "deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/xUbuntu_22.04/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:1.26.list

        sudo mkdir -p /usr/share/keyrings
        sudo curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg
        sudo curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.26/xUbuntu_22.04/Release.key | gpg --dearmor -o /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg

    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes
      register: result
      retries: 100
      delay: 10
      until: result is not failed

    - name: install cri-o only when the apt process isn't locked
      ansible.builtin.apt:
        name:
          - cri-o
          - cri-o-runc
        state: present
      register: result
      retries: 100
      delay: 10
      until: result is not failed

    - name: start cri-o
      ansible.builtin.shell: |
        sudo systemctl daemon-reload
        sudo systemctl enable crio
        sudo systemctl start crio

    - name: sysctl params setup
      copy:
        dest: "/etc/sysctl.d/99-kubernetes-cri.conf"
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: apply new settings, again
      ansible.builtin.shell: |
        sudo sysctl --system

    - name: configure dependencies and add k8 repos
      ansible.builtin.shell: |
        sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://dl.k8s.io/apt/doc/apt-key.gpg
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes
      register: result
      retries: 100
      delay: 10
      until: result is not failed

    - name: install kubelet, kubeadm and kubectl only when the apt process isn't locked
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
      register: result
      retries: 100
      delay: 10
      until: result is not failed

    - name: pin kubelet, kubeadm and kubectl versions
      ansible.builtin.shell: |
        sudo apt-mark hold kubelet kubeadm kubectl

- hosts: masters
  become: yes

  tasks:
    - name: initialise cluster with kubeadm in master node
      ansible.builtin.shell: |
        sudo kubeadm init

    - name: setup kubectl access as normal user
      become: yes
      become_user: jay
      ansible.builtin.shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: setup CNI, giving Weave Net a go
      become: yes
      become_user: jay
      ansible.builtin.shell: |
        kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

    - name: generate the token for joining the worker nodes
      become: yes
      become_user: jay
      ansible.builtin.shell: |
        kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: write join command to a file
      become: yes
      copy:
        dest: "/tmp/kubernetes_join_command.sh"
        content: "{{ kubernetes_join_command.stdout_lines[0] }}"

    - name: fetch join command file to the deploying machine
      become: yes
      ansible.builtin.fetch:
        src: "/tmp/kubernetes_join_command.sh"
        dest: "/tmp/kubernetes_join_command.sh"
        flat: yes

- hosts: workers
  become: yes

  tasks:
    - name: copy k8 cluster join code into worker nodes
      become: yes
      copy:
        src: /tmp/kubernetes_join_command.sh
        dest: /tmp/kubernetes_join_command.sh
        owner: root
        mode: 0777

    - name: join the Worker nodes to the cluster.
      become: yes
      become_user: jay
      ansible.builtin.shell: |
        sudo sh /tmp/kubernetes_join_command.sh
      register: joined_or_not